# Generated by Django 4.0.4 on 2022-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=30)),
                ('taskdesc', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
